### ISSUE TITLE
Add new rows in runtime

### ISSUE THREAD

**Issue by Mocio89** [David-PLC/CWC-Table#1]
Hi, good work.
Is it possible to add new rows in runtime?
For example populating the table with the result of a sql query . Could u provide some examples?
Thanks

**Comment by David-PLC** [comment]
Hi, of course you can, here is an example:

- Let's say you have done a query to a table with 3 columns named [Name,Value,TimeStamp]
- After you have done the query you have to push the data into an array like:
`let dataArr = [];`
`for (let i = 0; i < data.length; i++) {`
` dataArr.push([data[i].Name, data[i].Value, data[i].TimeStamp]);`
`}`
- The you have to stringify tour array like:
` dataArr = JSON.stringify(dataArr);`
- Now you can take your variable "dataArr" and move it to the "rows" of the table like:
` Screen.FindItem('Your_Table_Name').Properties.rows = dataArr ;`

I hope this help you! if you need more info i'm here!
