### ISSUE TITLE
Example of using the control

### ISSUE THREAD

**Issue by falottec** [David-PLC/CWC-Table#4]
Hi David,

could you provide an example of how to use the control in WinCC unified. More specifically, how to access and set the rows property of the control's Interface. I am able to provide a static data to rows via WinCC Inspector window, however I am not able to change the rows property dynamically from the code in run-time.

Do I need to change something in control's source code (var production= true;)?

Thank you

**Comment by David-PLC** [comment]
Hi!
All this information has been written in the Readme file, anyway i'll give you an example.

The line with "var production= true;" has to be set on true to let the CWCW work with unified, ther "false" option is only used to test the CWC in visual studio code using Live Server.

Can you be more specific about the data format you are trying to show on the table?

**Comment by David-PLC** [comment]
I'm going to fix the Readme file to specify that the - "rows" values have to be passed with string.
At the moment I've used strings and I didn't have any issues, but I'm constantly updating those CWC so maybe I will try to use Arrays to see if it's better!

Thank you for your contribution!
